[package]
name = "noa_debugger_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
noa_runtime = { path = "../runtime", version = "0.1.0" }
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
